#!/bin/bash

set -e

# for some reason at upgrade time a directory is not
# replaced by a symlink provided by the new package

if [ ! -h /usr/lib/perl5/auto/Apache/include ]; then
	cd /
	rm -rf /usr/lib/perl5/auto/Apache/include
	ln -sf ../../../../include/apache-1.3 usr/lib/perl5/auto/Apache/include
fi

# apache-perl does not need us as DSO

for i in apache apache-ssl; do
	if [ -e /etc/$i/httpd.conf ]; then
		apache-modconf $i enable mod_perl
	fi
done

#DEBHELPER#

exit 0
