#!/usr/bin/perl -lpw

s?_log?.log?g;
s?apache.conf?httpd.conf?g;

s?usr/local/bin/perl?usr/bin/perl?g;

# bug?
s?TH ab 1?TH ab 8?;
s?TH apachectl 1?TH apachectl 8?;

# debian convention
s?TH apxs 8?TH apxs 1?;
s?TH httpd 8?TH apache 8?;
s?httpd\(8\)?apache\(8\)?;
s?B httpd?B apache?;
s?^httpd?apache?;
s?httpd -l?apache -l?;

# manual fix
s?\"apache_pb.gif\"?\"icons/apache_pb.gif\"?;

# mime.types in apaci
s?/etc/apache/mime.types?/etc/mime.types?;

#apachectl
s?/usr/local/apache/logs/httpd.pid?/var/run/apache.pid?;
s?/usr/local/apache/src/httpd?/usr/sbin/apache?;

#manpages
s?/usr/local/httpd.conf?/etc/apache?;
s?/usr/local/apache/logs?/var/log/apache?;

#lynx/www-browser
s?"lynx?"/etc/alternatives/www-browser?;
